version: "3.7"
# Los valores como ${DB_USER} se leen del .env
services:
  web-verifier-plus:
    container_name: web-verifier-plus
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - HEALTH_CHECK_SMTP_HOST=add your email host, like smtp.sendgrid.net
      - HEALTH_CHECK_SMTP_USER=
      - HEALTH_CHECK_SMTP_PASS=
      - HEALTH_CHECK_EMAIL_FROM=Digital Credentials Consortium Demo Issuer <DCC-support@mit.edu>
      - HEALTH_CHECK_EMAIL_RECIPIENT=the email addresss of whoever should receive unhealthy notications
      - HEALTH_CHECK_EMAIL_SUBJECT="DCC Dashboard Issuer Coordinator Microservice Healthcheck"
      - HEALTH_CHECK_WEB_HOOK=a webhook like those of Slack
      - HEALTH_CHECK_SERVICE_URL=http://localhost:3000/api/healthz - the healthz endpoint
      - HEALTH_CHECK_SERVICE_NAME=VERIFIER-PLUS
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
    healthcheck:
      test: ["CMD", "node", "healthcheck.mjs"]
      interval: 30m
      retries: 3
      start_period: 30s
      timeout: 80s
    ports:
      - "3010:3000"
    labels:
      autoheal: true
  autoheal:
    image: willfarrell/autoheal:latest
    restart: always
    environment:
      - AUTOHEAL_INTERVAL=60
      - AUTOHEAL_START_PERIOD=30
      - WEBHOOK_URL=an optional webhook to report restarts
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 3015:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASS}
      ME_CONFIG_MONGODB_URL: mongodb://${DB_USER}:${DB_PASS}@mongo:27017/
      ME_CONFIG_BASICAUTH: "false"
